/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.matriz.filial;

import controller.CategoriaController;
import controller.FilialController;
import controller.ProdutoController;
import java.util.List;
import javax.swing.JOptionPane;
import jpa.Categoria;
import jpa.ItemCarrinho;
import jpa.Produto;

/**
 *
 * @author Calebe de Paula Bianchini
 */
public class RelacionarFilialGUI extends javax.swing.JFrame {
    
    private FilialController    filialController    = null;
    private CategoriaController categoriaController = null;
    private ProdutoController   produtoController   = null;
    private List<ItemCarrinho>        filiaisProduto;
    private List<ItemCarrinho>        filiaisIncluir;
    private List<Produto>       produtos;
    private List<Categoria>     categorias;
    private Categoria           categoria;
    private Produto             produto;
    private ItemCarrinho              filialProduto;
    private ItemCarrinho              filialIncluir;

    
    /**
     * Creates new form ContatoGUI
     */
    public RelacionarFilialGUI() {
        initComponents();
        setComboCategoria(comboCategoria);
        setComboProduto(comboProduto);
        setComboTodasFiliais(comboTodasFiliais);
        setComboFiliaisProduto(comboFiliaisProduto);
        updateTable();
    }
    
    //tabela com as categorias
    private void updateTable() {
        try {
            if (filialController == null) {
                filialController = new FilialController();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao conectar com o servidor...");
            botaoIncluirFilial.setEnabled(false);
            botaoRetirarFilial.setEnabled(false);
            
            return;
        }
        
        
        if (produto.getFiliais()!=null) {
            filiaisProduto = (List)produto.getFiliais();
        ItemCarrinho[] fil = produto.getFiliais().toArray(new ItemCarrinho[0]);
        Object[][] objects = new Object[fil.length][2];
        for (int i = 0; i < fil.length; i++) {
            objects[i][0] = fil[i].getNome();
            objects[i][1] = fil[i].getId();
        }
        tblFiliais.setModel(new javax.swing.table.DefaultTableModel(
                objects,
                new String[]{ "Nome", "ID" }));
        } else return;
        
        //txtNome.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        itsolution_logo = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();
        nomeCategoriaText3 = new javax.swing.JLabel();
        comboCategoria = new javax.swing.JComboBox();
        nomeCategoriaText4 = new javax.swing.JLabel();
        comboProduto = new javax.swing.JComboBox();
        panelIncluirCategoria1 = new javax.swing.JPanel();
        botaoIncluirFilial = new javax.swing.JButton();
        comboTodasFiliais = new javax.swing.JComboBox();
        nomeCategoriaText5 = new javax.swing.JLabel();
        panelIncluirCategoria2 = new javax.swing.JPanel();
        botaoRetirarFilial = new javax.swing.JButton();
        comboFiliaisProduto = new javax.swing.JComboBox();
        nomeCategoriaText6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFiliais = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Contatos");

        title.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Produto x Filial");
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        itsolution_logo.setText("ITSolution");

        botaoVoltar.setText("Voltar");
        botaoVoltar.setToolTipText("");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        nomeCategoriaText3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nomeCategoriaText3.setText("Categoria:");

        comboCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCategoriaItemStateChanged(evt);
            }
        });

        nomeCategoriaText4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nomeCategoriaText4.setText("Produto:");

        comboProduto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboProdutoItemStateChanged(evt);
            }
        });
        comboProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProdutoActionPerformed(evt);
            }
        });

        panelIncluirCategoria1.setBorder(javax.swing.BorderFactory.createTitledBorder("Incluir"));

        botaoIncluirFilial.setText("Incluir");
        botaoIncluirFilial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIncluirFilialActionPerformed(evt);
            }
        });

        comboTodasFiliais.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTodasFiliaisItemStateChanged(evt);
            }
        });
        comboTodasFiliais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTodasFiliaisActionPerformed(evt);
            }
        });

        nomeCategoriaText5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nomeCategoriaText5.setText("Filial:");

        javax.swing.GroupLayout panelIncluirCategoria1Layout = new javax.swing.GroupLayout(panelIncluirCategoria1);
        panelIncluirCategoria1.setLayout(panelIncluirCategoria1Layout);
        panelIncluirCategoria1Layout.setHorizontalGroup(
            panelIncluirCategoria1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIncluirCategoria1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelIncluirCategoria1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoIncluirFilial)
                    .addGroup(panelIncluirCategoria1Layout.createSequentialGroup()
                        .addComponent(nomeCategoriaText5)
                        .addGap(18, 18, 18)
                        .addComponent(comboTodasFiliais, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelIncluirCategoria1Layout.setVerticalGroup(
            panelIncluirCategoria1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIncluirCategoria1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIncluirCategoria1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCategoriaText5)
                    .addComponent(comboTodasFiliais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoIncluirFilial)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelIncluirCategoria2.setBorder(javax.swing.BorderFactory.createTitledBorder("Retirar"));

        botaoRetirarFilial.setText("Retirar");
        botaoRetirarFilial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRetirarFilialActionPerformed(evt);
            }
        });

        comboFiliaisProduto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboFiliaisProdutoItemStateChanged(evt);
            }
        });
        comboFiliaisProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFiliaisProdutoActionPerformed(evt);
            }
        });

        nomeCategoriaText6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nomeCategoriaText6.setText("Filial:");

        javax.swing.GroupLayout panelIncluirCategoria2Layout = new javax.swing.GroupLayout(panelIncluirCategoria2);
        panelIncluirCategoria2.setLayout(panelIncluirCategoria2Layout);
        panelIncluirCategoria2Layout.setHorizontalGroup(
            panelIncluirCategoria2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIncluirCategoria2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelIncluirCategoria2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoRetirarFilial)
                    .addGroup(panelIncluirCategoria2Layout.createSequentialGroup()
                        .addComponent(nomeCategoriaText6)
                        .addGap(18, 18, 18)
                        .addComponent(comboFiliaisProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelIncluirCategoria2Layout.setVerticalGroup(
            panelIncluirCategoria2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIncluirCategoria2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelIncluirCategoria2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCategoriaText6)
                    .addComponent(comboFiliaisProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoRetirarFilial))
        );

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setEnabled(false);
        jScrollPane1.setFocusable(false);

        tblFiliais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Nome", "Telefone"
            }
        ));
        jScrollPane1.setViewportView(tblFiliais);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(itsolution_logo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nomeCategoriaText3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(panelIncluirCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nomeCategoriaText4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(panelIncluirCategoria2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itsolution_logo)
                    .addComponent(title))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeCategoriaText3)
                    .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeCategoriaText4)
                    .addComponent(comboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelIncluirCategoria1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelIncluirCategoria2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-615)/2, (screenSize.height-465)/2, 615, 465);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        dispose();
        new GUI.matriz.MatrizInicial().setVisible(true);
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void comboProdutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboProdutoItemStateChanged
        if ( produto == null || produto != comboProduto.getSelectedItem()) {
            produtos = (List)categoria.getProdutos();
            produto = (Produto)comboProduto.getSelectedItem();
        }
        if(produto != null ){
            updateTable();
            //setComboFilialRetirar
        }
    }//GEN-LAST:event_comboProdutoItemStateChanged

    private void comboProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboProdutoActionPerformed

    private void comboCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCategoriaItemStateChanged
        for(Categoria categ: categorias){
            if(categ.getNome().equals(comboCategoria.getSelectedItem())) {
                categoria = categ;
                setComboProduto(comboProduto);
            }
        }
    }//GEN-LAST:event_comboCategoriaItemStateChanged

    private void botaoIncluirFilialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIncluirFilialActionPerformed
        if (produto.getFiliais().contains(filialIncluir)) {
            JOptionPane.showMessageDialog(null, "O produto " + produto.getNome() + " já tem a filial " + filialIncluir.getNome() + "!");
        } else {
            produto.getFiliais().add(filialIncluir);
            produtoController.edit(produto);
            setComboFiliaisProduto(comboFiliaisProduto);
            setComboTodasFiliais(comboTodasFiliais);
            updateTable();
        }

    }//GEN-LAST:event_botaoIncluirFilialActionPerformed

    private void botaoRetirarFilialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRetirarFilialActionPerformed
        
        produto.getFiliais().remove(filialProduto);
        produtoController.edit(produto);
        setComboFiliaisProduto(comboFiliaisProduto);
        setComboTodasFiliais(comboTodasFiliais);
        updateTable();
    }//GEN-LAST:event_botaoRetirarFilialActionPerformed

    private void comboTodasFiliaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTodasFiliaisActionPerformed
        //categoriaAtual = comboCategoria.getSelectedItem().toString();
    }//GEN-LAST:event_comboTodasFiliaisActionPerformed

    private void comboFiliaisProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFiliaisProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFiliaisProdutoActionPerformed

    private void comboTodasFiliaisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTodasFiliaisItemStateChanged
        for(ItemCarrinho f: filiaisIncluir){
            if(f.getNome().equals(comboTodasFiliais.getSelectedItem())) {
                filialIncluir = f;
            }
        }
    }//GEN-LAST:event_comboTodasFiliaisItemStateChanged

    private void comboFiliaisProdutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboFiliaisProdutoItemStateChanged
        for(ItemCarrinho f: filiaisProduto){
            if(f.getNome().equals(comboFiliaisProduto.getSelectedItem())) {
                filialProduto = f;
            }
        }
    }//GEN-LAST:event_comboFiliaisProdutoItemStateChanged

    public javax.swing.JComboBox getComboCategoria() {
        return comboCategoria;
    }
    /**
     * @param comboCategoria the comboCategoria to set
     */
    public void setComboCategoria(javax.swing.JComboBox comboCategoria) {
        this.comboCategoria = comboCategoria;
        try {
            if (categoriaController == null) {
                categoriaController = new CategoriaController();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao conectar com o servidor...");
            return;
        }
        categorias = categoriaController.findAll();
        comboCategoria.removeAllItems();

        for(Categoria categ: categorias){
            comboCategoria.addItem(categ.getNome());
        }
        for(Categoria categ: categorias){
            if(categoria.getNome().equals(comboCategoria.getSelectedItem())) {
                categoria = categ;
            }
        }
    }
    /**
     * @return the comboProduto
     */
    public javax.swing.JComboBox getComboProduto() {
        return comboProduto;
    }

    /**
     * @param comboProduto the comboProduto to set
     */
    
    public void setComboProduto(javax.swing.JComboBox comboProduto) {
        this.comboProduto = comboProduto;
        try {
            if (produtoController == null) {
                produtoController = new ProdutoController();
            }
            if (categoriaController == null){
                categoriaController = new CategoriaController();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao conectar com o servidor...");
            return;
        }
        for(Categoria categ: categorias){
            if(categ.getNome().equals(comboCategoria.getSelectedItem())){
                categoria = categ;
            }
        }
        produtos = (List)categoria.getProdutos();
        comboProduto.removeAllItems();
        for(Produto prod: produtos){
            comboProduto.addItem(prod);
        }
    }
    
    public void setComboTodasFiliais(javax.swing.JComboBox comboFilial) {
        try {
            if (filialController == null) {
                filialController = new FilialController();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao conectar com o servidor...");
            return;
        }
        
        filiaisIncluir = filialController.findAll();
        filtrarFiliaisInclusao();
        comboFilial.removeAllItems();

        for(ItemCarrinho f: filiaisIncluir){
            comboFilial.addItem(f.getNome());
        }
        
        for(ItemCarrinho f: filiaisIncluir){
            if(f.getNome().equals(comboTodasFiliais.getSelectedItem())) {
                filialIncluir = f;
            }
        }
        //comboCategoria.setModel(new javax.swing.DefaultComboBoxModel(categorias));
    }
    
    public void setComboFiliaisProduto(javax.swing.JComboBox comboFiliaisProduto) {
        try {
            if (filialController == null) {
                filialController = new FilialController();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao conectar com o servidor...");
            return;
        }
        
        
        filiaisProduto = (List)produto.getFiliais();
        comboFiliaisProduto.removeAllItems();
        
        for(ItemCarrinho f: filiaisProduto) {
            comboFiliaisProduto.addItem(f.getNome());
        }
        
        for(ItemCarrinho f: filiaisProduto){
            if(f.getNome().equals(comboFiliaisProduto.getSelectedItem())) {
                filialProduto = f;
            }
        }
        //comboCategoria.setModel(new javax.swing.DefaultComboBoxModel(categorias));
    }
    
    public void filtrarFiliaisInclusao(){
        for(ItemCarrinho f: filiaisProduto){
            if( filiaisIncluir.contains(f) ){
                filiaisIncluir.remove(f);
            }
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoIncluirFilial;
    private javax.swing.JButton botaoRetirarFilial;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JComboBox comboCategoria;
    private javax.swing.JComboBox comboFiliaisProduto;
    private javax.swing.JComboBox comboProduto;
    private javax.swing.JComboBox comboTodasFiliais;
    private javax.swing.JLabel itsolution_logo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomeCategoriaText3;
    private javax.swing.JLabel nomeCategoriaText4;
    private javax.swing.JLabel nomeCategoriaText5;
    private javax.swing.JLabel nomeCategoriaText6;
    private javax.swing.JPanel panelIncluirCategoria1;
    private javax.swing.JPanel panelIncluirCategoria2;
    private javax.swing.JTable tblFiliais;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
