/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.matriz.pedidos;

import GUI.matriz.categoria.*;
import controller.CategoriaController;
import controller.FilialController;
import controller.PedidoController;
import java.util.Collection;
import javax.swing.JOptionPane;
import jpa.Categoria;
import jpa.Filial;
import jpa.Pedido;

/**
 *
 * @author Calebe de Paula Bianchini
 */
public class EnviarPedidosGUI extends javax.swing.JFrame {

    private CategoriaController categoriaController = null;
    private PedidoController pedidoController = null;
    private FilialController filialController = null;
    private Collection<Filial> filiais;
    private Filial filial = null;
    private Collection<Pedido> pedidos;
    private Collection<Pedido> pedidosEnviar;
    private Pedido pedido = null;
    
    //private String categoriaAtual;

    /**
     * Creates new form ContatoGUI
     */
    public EnviarPedidosGUI() {
        initComponents();
        setComboFilial(comboFilial);
        setComboPedidos(comboPedidos);
    }

    //tabela com as categorias
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        itsolution_logo = new javax.swing.JLabel();
        panelIncluirCategoria = new javax.swing.JPanel();
        txtPedido = new javax.swing.JLabel();
        comboPedidos = new javax.swing.JComboBox();
        txtFilial = new javax.swing.JLabel();
        comboFilial = new javax.swing.JComboBox();
        botaoEnviarPedido = new javax.swing.JButton();
        botaoVoltarExcluirCategoria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Contatos");

        title.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Enviar Pedidos");
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        itsolution_logo.setText("ITSolution");

        panelIncluirCategoria.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txtPedido.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtPedido.setText("Pedido");

        comboPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPedidosActionPerformed(evt);
            }
        });

        txtFilial.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtFilial.setText("Filial:");

        comboFilial.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboFilialItemStateChanged(evt);
            }
        });
        comboFilial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFilialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIncluirCategoriaLayout = new javax.swing.GroupLayout(panelIncluirCategoria);
        panelIncluirCategoria.setLayout(panelIncluirCategoriaLayout);
        panelIncluirCategoriaLayout.setHorizontalGroup(
            panelIncluirCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIncluirCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIncluirCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPedido)
                    .addComponent(txtFilial))
                .addGap(18, 18, 18)
                .addGroup(panelIncluirCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboPedidos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboFilial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelIncluirCategoriaLayout.setVerticalGroup(
            panelIncluirCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIncluirCategoriaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelIncluirCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPedido)
                    .addComponent(comboPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIncluirCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFilial)
                    .addComponent(comboFilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        botaoEnviarPedido.setText("Enviar");
        botaoEnviarPedido.setToolTipText("");
        botaoEnviarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarPedidoActionPerformed(evt);
            }
        });

        botaoVoltarExcluirCategoria.setText("Voltar");
        botaoVoltarExcluirCategoria.setToolTipText("");
        botaoVoltarExcluirCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarExcluirCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                        .addComponent(itsolution_logo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoVoltarExcluirCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoEnviarPedido))
                    .addComponent(panelIncluirCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itsolution_logo)
                    .addComponent(title))
                .addGap(18, 18, 18)
                .addComponent(panelIncluirCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEnviarPedido)
                    .addComponent(botaoVoltarExcluirCategoria))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-585)/2, (screenSize.height-260)/2, 585, 260);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEnviarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnviarPedidoActionPerformed
        if (filial != null) {
            if (pedido != null) {
                this.pedido.setPedidoEnviadoCliente(true);
                pedidoController.edit(pedido);
            }
        }
        
    }//GEN-LAST:event_botaoEnviarPedidoActionPerformed

    private void comboPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPedidosActionPerformed
        
    }//GEN-LAST:event_comboPedidosActionPerformed

    private void botaoVoltarExcluirCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarExcluirCategoriaActionPerformed
        new GUI.matriz.MatrizInicial().setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoVoltarExcluirCategoriaActionPerformed

    private void comboFilialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFilialActionPerformed
        
    }//GEN-LAST:event_comboFilialActionPerformed

    private void comboFilialItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboFilialItemStateChanged
        filiais = filialController.findAll();
        
        if (filiais!=null && !filiais.isEmpty()) {
            for ( Filial filial: filiais ) {
                if ( filial.getNome().equals( comboFilial.getSelectedItem())) {
                    this.filial = filial;
                }
            }
        }
    }//GEN-LAST:event_comboFilialItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEnviarPedido;
    private javax.swing.JButton botaoVoltarExcluirCategoria;
    private javax.swing.JComboBox comboFilial;
    private javax.swing.JComboBox comboPedidos;
    private javax.swing.JLabel itsolution_logo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelIncluirCategoria;
    private javax.swing.JLabel title;
    private javax.swing.JLabel txtFilial;
    private javax.swing.JLabel txtPedido;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the comboCategoria
     */
    public javax.swing.JComboBox getComboCategoria() {
        return getComboPedidos();
    }

    /**
     * @param comboCategoria the comboCategoria to set
     */
    public void setComboFilial(javax.swing.JComboBox comboFilial) {
        setControllers();
        
        filiais = filialController.findAll();
        
        if (filiais!=null && !filiais.isEmpty()) {
            comboFilial.removeAllItems();
            for ( Filial filial: filiais ) {
                comboFilial.addItem(filial.getNome());
            }
            for ( Filial filial: filiais ) {
                if ( filial.getNome().equals(comboFilial.getSelectedItem().toString() )) {
                    this.filial = filial;
                }
            }
        }
        this.comboFilial = comboFilial;
    }

    /**
     * @return the comboPedidos
     */
    public javax.swing.JComboBox getComboPedidos() {
        return comboPedidos;
    }

    /**
     * @param comboPedidos the comboPedidos to set
     */
    public void setComboPedidos(javax.swing.JComboBox comboPedidos) {
        setControllers();
        filtraPedidos();
        if ( pedidosEnviar!= null ) {
            for (Pedido pedido: pedidosEnviar) {
                comboPedidos.addItem(pedido.getId());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Todos os pedidos ja foram encaminhados para as filiais.");
            botaoEnviarPedido.setEnabled(false);
            
        }
        this.comboPedidos = comboPedidos;
    }
    private void setControllers(){
        try {
            if (filialController == null) {
                filialController = new FilialController();
            }
            if (pedidoController == null) {
                pedidoController = new PedidoController();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao conectar com o servidor...");
            return;
        }
    }
    
    private void filtraPedidos(){
        setControllers();
        pedidos = pedidoController.findAll();
        
        if ( pedidos!= null ) {
            for (Pedido pedido: pedidos) {
                if ( !pedido.isPedidoEncaminhado() ) {
                    pedidosEnviar.add(pedido);
                }
            }
        }
    }
}
