/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.filial;

import GUI.matriz.filial.*;
import controller.FilialController;
import javax.swing.JOptionPane;
import jpa.Filial;

/**
 *
 * @author GPinzegher
 */
public class InicioGUI extends javax.swing.JFrame {

    private Filial filial;
    //private String categoriaAtual;

    /**
     * Creates new form ContatoGUI
     */
    public InicioGUI(Filial filial) {
        this.filial = filial;
        initComponents();
        title.setText("Filial " + this.filial.getNome());
    }

    //tabela com as categorias
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        itsolution_logo = new javax.swing.JLabel();
        panelIncluirCategoria = new javax.swing.JPanel();
        botaoVoltar1 = new javax.swing.JButton();
        botaoVoltar2 = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Contatos");

        title.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Filial");
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        itsolution_logo.setText("ITSolution");

        panelIncluirCategoria.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panelIncluirCategoria.setLayout(new java.awt.GridLayout());

        botaoVoltar1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        botaoVoltar1.setText("Gerenciar Estoque");
        botaoVoltar1.setToolTipText("");
        botaoVoltar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                botaoVoltar1MouseReleased(evt);
            }
        });
        botaoVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltar1ActionPerformed(evt);
            }
        });
        panelIncluirCategoria.add(botaoVoltar1);

        botaoVoltar2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        botaoVoltar2.setText("Vender");
        botaoVoltar2.setToolTipText("");
        botaoVoltar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                botaoVoltar2MouseReleased(evt);
            }
        });
        panelIncluirCategoria.add(botaoVoltar2);

        botaoVoltar.setText("Voltar");
        botaoVoltar.setToolTipText("");
        botaoVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                botaoVoltarMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 323, Short.MAX_VALUE)
                        .addComponent(itsolution_logo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoVoltar)
                        .addGap(24, 24, 24))
                    .addComponent(panelIncluirCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itsolution_logo)
                    .addComponent(title))
                .addGap(18, 18, 18)
                .addComponent(panelIncluirCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoVoltar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-499)/2, (screenSize.height-241)/2, 499, 241);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoltarMouseReleased
        new GUI.filial.FilialGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoVoltarMouseReleased

    private void botaoVoltar1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoltar1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoVoltar1MouseReleased

    private void botaoVoltar2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoltar2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoVoltar2MouseReleased

    private void botaoVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoVoltar1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JButton botaoVoltar1;
    private javax.swing.JButton botaoVoltar2;
    private javax.swing.JLabel itsolution_logo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelIncluirCategoria;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    
}
