/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.matriz;

import GUI.matriz.categoria.AlterarCategoriaGUI;
import GUI.matriz.categoria.ExcluirCategoriaGUI;
import GUI.matriz.categoria.InserirCategoriaGUI;
import GUI.matriz.produto.InserirProdutoGUI;



/**
 *
 * @author GPinzegher
 */
public class MatrizInicial extends javax.swing.JFrame {

    /**
     * Creates new form matrizInicial
     */
    public MatrizInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botaoSairMatriz = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        botaoProdutoIncluir = new javax.swing.JButton();
        botaoProdutoAlterar = new javax.swing.JButton();
        botaoProdutoExcluir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        botaoCategoriaIncluir = new javax.swing.JButton();
        botaoCategoriaAlterar = new javax.swing.JButton();
        botaoCategoriaExcluir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        botaoProdutoFilial = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        botaoFilialIncluir = new javax.swing.JButton();
        botaoFilialAlterar = new javax.swing.JButton();
        botaoFilialExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ITSolution - Matriz");
        setBounds(new java.awt.Rectangle(100, 100, 720, 480));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximizedBounds(new java.awt.Rectangle(100, 100, 720, 480));
        setMaximumSize(new java.awt.Dimension(720, 480));
        setMinimumSize(new java.awt.Dimension(720, 480));
        setPreferredSize(new java.awt.Dimension(720, 480));
        setResizable(false);

        jLabel1.setText("ITSolution");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setText("Matriz");

        botaoSairMatriz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoSairMatriz.setText("Sair");
        botaoSairMatriz.setActionCommand("incluirProdutoButton");
        botaoSairMatriz.setAlignmentX(15.0F);
        botaoSairMatriz.setAlignmentY(15.0F);
        botaoSairMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairMatrizActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        botaoProdutoIncluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoProdutoIncluir.setText("Incluir");
        botaoProdutoIncluir.setActionCommand("incluirProdutoButton");
        botaoProdutoIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProdutoIncluirActionPerformed(evt);
            }
        });

        botaoProdutoAlterar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoProdutoAlterar.setText("Alterar");
        botaoProdutoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProdutoAlterarActionPerformed(evt);
            }
        });

        botaoProdutoExcluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoProdutoExcluir.setText("Excluir");
        botaoProdutoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProdutoExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoProdutoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoProdutoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoProdutoIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoProdutoIncluir)
                .addGap(18, 18, 18)
                .addComponent(botaoProdutoAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoProdutoExcluir)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categoria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        botaoCategoriaIncluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoCategoriaIncluir.setText("Incluir");
        botaoCategoriaIncluir.setActionCommand("incluirProdutoButton");
        botaoCategoriaIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCategoriaIncluirActionPerformed(evt);
            }
        });

        botaoCategoriaAlterar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoCategoriaAlterar.setText("Alterar");
        botaoCategoriaAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCategoriaAlterarActionPerformed(evt);
            }
        });

        botaoCategoriaExcluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoCategoriaExcluir.setText("Excluir");
        botaoCategoriaExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCategoriaExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoCategoriaExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(botaoCategoriaIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoCategoriaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoCategoriaIncluir)
                .addGap(18, 18, 18)
                .addComponent(botaoCategoriaAlterar)
                .addGap(18, 18, 18)
                .addComponent(botaoCategoriaExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton9.setText("Diário");
        jButton9.setActionCommand("incluirProdutoButton");
        jButton9.setMaximumSize(new java.awt.Dimension(83, 31));
        jButton9.setMinimumSize(new java.awt.Dimension(83, 31));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton10.setText("Mensal");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        botaoProdutoFilial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoProdutoFilial.setText("Produto x Filial");
        botaoProdutoFilial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProdutoFilialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoProdutoFilial)
                .addGap(35, 35, 35))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10)
                    .addComponent(botaoProdutoFilial))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filial", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        botaoFilialIncluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoFilialIncluir.setText("Incluir");
        botaoFilialIncluir.setActionCommand("incluirProdutoButton");
        botaoFilialIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFilialIncluirActionPerformed(evt);
            }
        });

        botaoFilialAlterar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoFilialAlterar.setText("Alterar");
        botaoFilialAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFilialAlterarActionPerformed(evt);
            }
        });

        botaoFilialExcluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoFilialExcluir.setText("Excluir");
        botaoFilialExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFilialExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoFilialExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(botaoFilialIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoFilialAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoFilialIncluir)
                .addGap(18, 18, 18)
                .addComponent(botaoFilialAlterar)
                .addGap(18, 18, 18)
                .addComponent(botaoFilialExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoSairMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(botaoSairMatriz)
                .addGap(16, 16, 16))
        );

        jPanel4.getAccessibleContext().setAccessibleName("Controles");
        jPanel6.getAccessibleContext().setAccessibleDescription("");

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoProdutoIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProdutoIncluirActionPerformed
        new GUI.matriz.produto.InserirProdutoGUI().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_botaoProdutoIncluirActionPerformed

    private void botaoProdutoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProdutoAlterarActionPerformed
        new GUI.matriz.produto.AlterarProdutoGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoProdutoAlterarActionPerformed

    private void botaoCategoriaIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCategoriaIncluirActionPerformed
        new GUI.matriz.categoria.InserirCategoriaGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoCategoriaIncluirActionPerformed

    private void botaoCategoriaAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCategoriaAlterarActionPerformed
        new GUI.matriz.categoria.AlterarCategoriaGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoCategoriaAlterarActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void botaoSairMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairMatrizActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botaoSairMatrizActionPerformed

    private void botaoCategoriaExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCategoriaExcluirActionPerformed
        new GUI.matriz.categoria.ExcluirCategoriaGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoCategoriaExcluirActionPerformed

    private void botaoProdutoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProdutoExcluirActionPerformed
        dispose();
        new GUI.matriz.produto.ExcluirProdutoGUI().setVisible(true);
        
    }//GEN-LAST:event_botaoProdutoExcluirActionPerformed

    private void botaoProdutoFilialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProdutoFilialActionPerformed
        new GUI.matriz.filial.RelacionarFilialGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoProdutoFilialActionPerformed

    private void botaoFilialIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFilialIncluirActionPerformed
        new GUI.matriz.filial.InserirFilialGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoFilialIncluirActionPerformed

    private void botaoFilialAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFilialAlterarActionPerformed
        new GUI.matriz.filial.AlterarFilialGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoFilialAlterarActionPerformed

    private void botaoFilialExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFilialExcluirActionPerformed
        new GUI.matriz.filial.ExcluirFilialGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoFilialExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatrizInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatrizInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatrizInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatrizInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatrizInicial().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCategoriaAlterar;
    private javax.swing.JButton botaoCategoriaExcluir;
    private javax.swing.JButton botaoCategoriaIncluir;
    private javax.swing.JButton botaoFilialAlterar;
    private javax.swing.JButton botaoFilialExcluir;
    private javax.swing.JButton botaoFilialIncluir;
    private javax.swing.JButton botaoProdutoAlterar;
    private javax.swing.JButton botaoProdutoExcluir;
    private javax.swing.JButton botaoProdutoFilial;
    private javax.swing.JButton botaoProdutoIncluir;
    private javax.swing.JButton botaoSairMatriz;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
