/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.filial.estoque;

import controller.CategoriaController;
import controller.FilialController;
import controller.ProdutoController;
import java.util.Collection;
import java.util.List;
import javax.swing.JOptionPane;
import jpa.Categoria;
import jpa.Filial;
import jpa.Produto;


/**
 *
 * @author GPinzegher
 */
public class EstoqueProdutoGUI extends javax.swing.JFrame {
    
    private ProdutoController produtoController = null;
    private FilialController filialController = null;
    private Collection<Produto> produtos;
    private Produto produto;
    private Filial filial;
    
    /**
     * @author GPinzegher
     */
    
    public EstoqueProdutoGUI(Filial filial) {
        this.filial = filial;
        initComponents();
        titleFilial.setText(filial.getNome());
        setComboProduto(comboProduto);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleFilial = new javax.swing.JLabel();
        itsolution_logo = new javax.swing.JLabel();
        panelIncluirCategoria = new javax.swing.JPanel();
        nomeCategoriaText = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        nomeCategoriaText1 = new javax.swing.JLabel();
        txtDescricao = new java.awt.TextArea();
        nomeCategoriaText2 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        numeroQuantidade = new javax.swing.JSpinner();
        labelQuantidade = new javax.swing.JLabel();
        nomeCategoriaText4 = new javax.swing.JLabel();
        comboProduto = new javax.swing.JComboBox();
        botaoVoltar = new javax.swing.JButton();
        botaoAlterar = new javax.swing.JButton();
        title1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Contatos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(0, 0));

        titleFilial.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        titleFilial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleFilial.setText(" ");
        titleFilial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        itsolution_logo.setText("ITSolution");

        panelIncluirCategoria.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        nomeCategoriaText.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nomeCategoriaText.setText("Nome:");

        txtNome.setEditable(false);
        txtNome.setEnabled(false);

        nomeCategoriaText1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nomeCategoriaText1.setText("Descrição:");

        txtDescricao.setEditable(false);
        txtDescricao.setEnabled(false);

        nomeCategoriaText2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nomeCategoriaText2.setText("Preço:");

        txtPreco.setEditable(false);
        txtPreco.setEnabled(false);

        labelQuantidade.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelQuantidade.setText("Quantidade:");

        javax.swing.GroupLayout panelIncluirCategoriaLayout = new javax.swing.GroupLayout(panelIncluirCategoria);
        panelIncluirCategoria.setLayout(panelIncluirCategoriaLayout);
        panelIncluirCategoriaLayout.setHorizontalGroup(
            panelIncluirCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIncluirCategoriaLayout.createSequentialGroup()
                .addGroup(panelIncluirCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIncluirCategoriaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panelIncluirCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeCategoriaText1)
                            .addComponent(nomeCategoriaText)
                            .addComponent(nomeCategoriaText2)))
                    .addGroup(panelIncluirCategoriaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelQuantidade)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIncluirCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIncluirCategoriaLayout.createSequentialGroup()
                        .addGroup(panelIncluirCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelIncluirCategoriaLayout.createSequentialGroup()
                                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 325, Short.MAX_VALUE)))
                        .addGap(32, 32, 32))
                    .addGroup(panelIncluirCategoriaLayout.createSequentialGroup()
                        .addComponent(numeroQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelIncluirCategoriaLayout.setVerticalGroup(
            panelIncluirCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIncluirCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIncluirCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCategoriaText)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIncluirCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeCategoriaText1)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(panelIncluirCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCategoriaText2)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIncluirCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelQuantidade))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        nomeCategoriaText4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nomeCategoriaText4.setText("Produto:");

        comboProduto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboProdutoItemStateChanged(evt);
            }
        });

        botaoVoltar.setText("Voltar");
        botaoVoltar.setToolTipText("");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoAlterar.setText("Alterar");
        botaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarActionPerformed(evt);
            }
        });

        title1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setText("Alterar Estoque x Produto");
        title1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(titleFilial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(itsolution_logo))
                    .addComponent(panelIncluirCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nomeCategoriaText4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(title1)
                    .addContainerGap(85, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itsolution_logo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleFilial)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCategoriaText4)
                    .addComponent(comboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelIncluirCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAlterar)
                    .addComponent(botaoVoltar))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addComponent(title1)
                    .addContainerGap(339, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-650)/2, (screenSize.height-500)/2, 650, 500);
    }// </editor-fold>//GEN-END:initComponents
    
    private void setControllers(){
        try {
            if (produtoController == null) {
                produtoController = new ProdutoController();
            }
            if (filialController == null) {
                filialController = new FilialController();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao conectar com o servidor...");
            return;
        }
    }
    private void botaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarActionPerformed

        //Categoria categoria = (Categoria)comboCategoria.getSelectedItem();
        //Produto produto = (Produto)comboProduto.getSelectedItem();
        setControllers();
        
        try {
            
            produto.setDescricao(txtDescricao.getText());
            produto.setNome(txtNome.getText());
            produto.setPreco(txtPreco.getText());
            int quantidade = Integer.parseInt(numeroQuantidade.getValue().toString() );
            produto.setQuantidade( quantidade );
            Collection<Produto> produtosAtualizado = produtos;
            produtosAtualizado.removeAll(produtos);
            for(Produto p: produtos) {
                if ( p.getNome().equals(produto.getNome()) ) {
                    p.setQuantidade( quantidade );
                    
                }
                produtosAtualizado.add(p);
            }
            filial.setProdutos(produtosAtualizado);
            
            JOptionPane.showMessageDialog(null, "Estoque do produto " + produto.getNome() + " alterado com sucesso.");
            new GUI.filial.InicioGUI(filial).setVisible(true);
            dispose();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao alterar produto: " + produto.getNome());
        }
    }//GEN-LAST:event_botaoAlterarActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        dispose();
        new GUI.filial.InicioGUI(filial).setVisible(true);
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        
    }//GEN-LAST:event_formWindowOpened

    private void comboProdutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboProdutoItemStateChanged
        if ( filial != null ) {
            produtos = filial.getProdutos();
            if ( produtos != null  ) {
                for ( Produto p: produtos ) {
                    if ( comboProduto.getSelectedItem().equals(p.getNome()) ) {
                        produto = p;
                        txtNome.setText(produto.getNome());
                        txtDescricao.setText(produto.getDescricao());
                        txtPreco.setText(produto.getPreco());
                    }
                }
            }
        }
    }//GEN-LAST:event_comboProdutoItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlterar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JComboBox comboProduto;
    private javax.swing.JLabel itsolution_logo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelQuantidade;
    private javax.swing.JLabel nomeCategoriaText;
    private javax.swing.JLabel nomeCategoriaText1;
    private javax.swing.JLabel nomeCategoriaText2;
    private javax.swing.JLabel nomeCategoriaText4;
    private javax.swing.JSpinner numeroQuantidade;
    private javax.swing.JPanel panelIncluirCategoria;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel titleFilial;
    private java.awt.TextArea txtDescricao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JComboBox getComboProduto() {
        return comboProduto;
    }

    /**
     * @param comboProduto the comboProduto to set
     */
    public void setComboProduto(javax.swing.JComboBox comboProduto) {
        setControllers();
        if ( filial != null ) {
            produtos = filial.getProdutos();
            if (produtos != null) {
                this.comboProduto.removeAllItems();

                for (Produto p : produtos) {
                    comboProduto.addItem(p.getNome());
                }
                
                for (Produto p: produtos) {
                    if ( comboProduto.getSelectedItem().equals(p.getNome()) ){
                        produto = p;
                    }
                }
            }
        }
        
        
        this.comboProduto = comboProduto;
    }

    /**
     * @return the produtos
     */
    public Collection<Produto> getProdutos() {
        return produtos;
    }

    /**
     * @param produtos the produtos to set
     */
    public void setProdutos(Collection<Produto> produtos) {
        
        this.produtos = produtos;
    }
    

    /**
     * @param comboCategoria comboCategoria to set
     */
    

}
